version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url
        
phases:
  install:
    runtime-versions:
      python: 3.11
      
   
  pre_build:
    commands:
      - pip install -r aws-ci-cd-project/requirements.txt
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"

   
  build:
     commands:
      - cd aws-ci-cd-project
      - echo "Building Docker Image"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/aws-ci-cd-project:latest" .
    
    
  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/aws-ci-cd-project:latest"

      - echo "Docker Build & Push Completed Successfully!"

artifacts:
  files:
    - ['**/*']
  base-directory: .
